/* Generated By:JavaCC: Do not edit this line. analizadorPESPTreeConstants.java Version 5.0 */
public interface analizadorPESPTreeConstants
{
  public int JJTSTART = 0;
  public int JJTBLOQUE = 1;
  public int JJTVARIABLESGLOBALES = 2;
  public int JJTFUNCION = 3;
  public int JJTPARAMETROS = 4;
  public int JJTTIPO = 5;
  public int JJTSENTENCIAS = 6;
  public int JJTDECLARACIONES = 7;
  public int JJTDR = 8;
  public int JJTESTRUCTURADECISION = 9;
  public int JJTESTRUCTURAREPETITIVA = 10;
  public int JJTRETORNAVALOR = 11;
  public int JJTCOMPARACIONES = 12;
  public int JJTVALOR = 13;
  public int JJTOPERADORES = 14;
  public int JJTIMPRIMIR = 15;
  public int JJTLEER = 16;
  public int JJTLLAMARFUNCION = 17;
  public int JJTPARAMETROSFUNCION = 18;
  public int JJTANALIZARCALCULOS = 19;
  public int JJTEXPRESION = 20;
  public int JJTTERMINO = 21;
  public int JJTFACTOR = 22;
  public int JJTNUMERO = 23;
  public int JJTGETSYMBOL = 24;


  public String[] jjtNodeName = {
    "Start",
    "bloque",
    "variablesGlobales",
    "funcion",
    "parametros",
    "tipo",
    "sentencias",
    "declaraciones",
    "DR",
    "estructuraDecision",
    "estructuraRepetitiva",
    "retornaValor",
    "comparaciones",
    "valor",
    "operadores",
    "imprimir",
    "leer",
    "llamarFuncion",
    "parametrosFuncion",
    "analizarCalculos",
    "expresion",
    "termino",
    "factor",
    "numero",
    "getSymbol",
  };
}
/* JavaCC - OriginalChecksum=f1be00378209791fcf35b157f1155afb (do not edit this line) */
