/* Generated By:JJTree&JavaCC: Do not edit this line. analizadorPESPConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface analizadorPESPConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PROGRAMA = 1;
  /** RegularExpression Id. */
  int FUNCION = 2;
  /** RegularExpression Id. */
  int IF = 3;
  /** RegularExpression Id. */
  int ELSE = 4;
  /** RegularExpression Id. */
  int WHILE = 5;
  /** RegularExpression Id. */
  int RETURN = 6;
  /** RegularExpression Id. */
  int CONST = 7;
  /** RegularExpression Id. */
  int VAR = 8;
  /** RegularExpression Id. */
  int PARENIZQ = 9;
  /** RegularExpression Id. */
  int PARENDER = 10;
  /** RegularExpression Id. */
  int LLAVEIZQ = 11;
  /** RegularExpression Id. */
  int LLAVEDER = 12;
  /** RegularExpression Id. */
  int ASIGNACION = 13;
  /** RegularExpression Id. */
  int MENOR = 14;
  /** RegularExpression Id. */
  int MAYOR = 15;
  /** RegularExpression Id. */
  int NEGACION = 16;
  /** RegularExpression Id. */
  int IGUALDAD = 17;
  /** RegularExpression Id. */
  int COMA = 18;
  /** RegularExpression Id. */
  int SEMICOLON = 19;
  /** RegularExpression Id. */
  int SUMA = 20;
  /** RegularExpression Id. */
  int RESTA = 21;
  /** RegularExpression Id. */
  int MULTIPLICACION = 22;
  /** RegularExpression Id. */
  int DIVISION = 23;
  /** RegularExpression Id. */
  int READ = 24;
  /** RegularExpression Id. */
  int PRINT = 25;
  /** RegularExpression Id. */
  int INT = 26;
  /** RegularExpression Id. */
  int STRING = 27;
  /** RegularExpression Id. */
  int BOOLEAN = 28;
  /** RegularExpression Id. */
  int NUMBER = 29;
  /** RegularExpression Id. */
  int TEXT = 30;
  /** RegularExpression Id. */
  int VALBOOL = 31;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 32;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"programa\"",
    "\"funcion\"",
    "\"si\"",
    "\"sino\"",
    "\"mientras\"",
    "\"retorna\"",
    "\"const\"",
    "\"var\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\"!=\"",
    "\"==\"",
    "\",\"",
    "\";\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"leer\"",
    "\"imprime\"",
    "\"entero\"",
    "\"cadena\"",
    "\"booleano\"",
    "<NUMBER>",
    "<TEXT>",
    "<VALBOOL>",
    "<IDENTIFICADOR>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 37>",
  };

}
